spring.application.name=demo

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/banco_teste}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update  
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}

pluggy.client.id=${PLUGGY_CLIENT_ID:c20d196e-2cc3-45a5-8fa0-1f3bf6224937}
pluggy.client.secret=${PLUGGY_CLIENT_SECRET:SUA_CHAVE_SECRET_AQUI}
